### ISSUE TITLE
Why Entities.HashTags returns SymbolEntity array instead of HashTagEntity array? 

### ISSUE THREAD

**Issue by kumar8600** [CoreTweet/CoreTweet#101]
> http://coretweet.github.io/docs/classCoreTweet_1_1Entities.html

CoreTweet returns `SymbolEntity` array. In contrast, other entities have special classes for each.

I'm feeling inconvenience because `SymbolEntity` have no any functions to discriminate between hash tag and symbol.

In the first place, __symbol is not hash tag. In twitter API, `symbols` means financial symbols.__

> https://dev.twitter.com/overview/api/entities-in-twitter-objects#symbols

So we should not represent hash tag entities by `SymbolEntity`. Let's create `HashTagEntity` class and alter with it!

**Comment by azyobuzin** [comment]
`symbols` in entities is called Cashtag. I think both hashtag and cashtag can be called Symbol.

**Comment by kumar8600** [comment]
I think so too. But if you think so, you should create `CashTagEntity` and `HashTagEntity` classes inherit from `SymbolEntity`.

I want to say even if two concepts have same properties, you shouldn't represent them by same one class.

**Comment by kumar8600** [comment]
Great. Thank you!! :sushi: :sushi: :sushi:
