### ISSUE TITLE
StatusMessage.Message.Status.User.Idの値が本来のUserIdと一致しない

### ISSUE THREAD

**Issue by vias722** [CoreTweet/CoreTweet#119]
こちらの環境は
Windows7 SP1
Xamarin Studio Mono/.Net4.0 です。
StreamingApi.Userを使用して取得したStatusMessage内の発言者のUserIdが本来のUserIdとは異なる値になってしまいます。

**Comment by chitoku-k** [comment]
- 何を以って異なる値となりますか？（A で取得したデータと B で取得したデータが食い違う、など）
- 何らかの不具合により、Twitter の Streaming API はユーザー ID に null を格納して返す場合があるようです
- 常に再現する不具合であれば詳細をお教えください

**Comment by cannorin** [comment]
please show us...
- the code or raw JSON data that reproduces the bug.
- exact error messages.
- anything important you think.

**Comment by vias722** [comment]
申し訳ありません、ちょっと忙しくこちらに報告の途中であったことをすっかり忘れていました。
検証しましたところ、動作には問題がなかった可能性が高いのですが、自分の遭遇した現象を念のため報告しておきます。
今回再現のため使用したコードは以下の通りです。

using System;
using System.Linq;
using CoreTweet;
using CoreTweet.Streaming;

namespace CoreTweettest
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			var s = OAuth.Authorize ("S0B41nTEIdZLRf62Opwgr9kJK", "XihmIfIm9TTkyx7j7aCttf6x2G1DJRKuQDq9fUMvoRWIWst8VW");
			Console.WriteLine ("{0}", s.AuthorizeUri);
			var t = s.GetTokens (Console.ReadLine ());
			var messages = t.Streaming.User ();
			foreach (var mes in messages.OfType<StatusMessage>()) {
				Console.WriteLine ("mes.Status.User ID:{0} ScreenName:{1}", mes.Status.User.Id, mes.Status.User.ScreenName);
				Console.WriteLine ("t UserID:{0} ScreenName:{1}",t.UserId,t.ScreenName);
				Console.WriteLine ("mes.Status.Entities.UserMentions.First () ID:{0} ScreenName:{1}", mes.Status.Entities.UserMentions.First ().Id, mes.Status.Entities.UserMentions.First ().ScreenName);

			}
		}
	}
}

Result (Mention itself)：
mes.Status.User ID:3859047260 ScreenName:formyapptest
t UserID:3859047260 ScreenName:formyapptest
mes.Status.Entities.UserMentions.First () ID:3859047260 ScreenName:formyapptest

このコードを実行中に、連携を許可したアカウントで自分自身に向けてメンションを行った際のStatusMessageは全てのId,ScreenNameは同じ値を取るはずで、実際そうなりました。

ところがこのコードの17行目 Console.WriteLine ("mes.Status.User...の前にbreakpointを設定してその状態で変数を確認すると以下の画像のようになっており、User.IDの値が正しくないのではないかと勘違いをしてしまいました。
https://gyazo.com/34096c6f9874978e85d1d12de606bce8 (my local Variable Window when breaking at Line17)

コードとしては正しく動いていたのでCoretweetのバグというよりはXamarin Studioのバグの可能性が高いと思います。お待たせした結果こちらの勘違いのようで申し訳ないです。

**Comment by azyobuzin** [comment]
そうですね、 User の `{3859047260}` は `User.ToString()` の値（Idを返す）ですので、 デバッガーの問題とみて良いと思います。

CoreTweet のバグではなさそうなのでクローズさせていただきます。

**Comment by cannorin** [comment]
Masked the consumer keys(it shouldn't be open)

**Comment by vias722** [comment]
Oh,sorry. I forgot to mask them. I'll generate new keys later.
