### ISSUE TITLE
Search.Tweets throw exception when query contains colon

### ISSUE THREAD

**Issue by cucmberium** [CoreTweet/CoreTweet#120]
Universal Windows Platform環境においてクエリに":"を含む検索ができないようです.
検索しようとするとSystem.Runtime.InteropServices.COMExceptionの例外が発生します.

環境はWindows 10 build 10547 (10240でも同様の症状を確認)
CoreTweetのバージョンは0.5.4-beta2です.

再現コードは以下のものです.
```cs
var search = await token.Search.TweetsAsync(q => "島風 filter:images", count => 20);
```

**Comment by azyobuzin** [comment]
COMException
```
要素が見つかりません。

親ウィンドウ ハンドルが設定されていないため、ダイアログを表示できません。
```
という例外が出ましたが、これでしょうか？確かに ":" が含まれる検索でのみ発生しますが、エラーメッセージから推測が難しいですね。
