### ISSUE TITLE
提案: APIの説明を短くする

### ISSUE THREAD

**Issue by azyobuzin** [CoreTweet/CoreTweet#121]
ApiTemplates の中には description がとても長いのがありますが、 IntelliSense への表示を考えると最小限のことだけを書くべきだと思います。

（<q>You don't have to learn about CoreTweet's API; just learn about Twitter's API.</q> だし）

ご意見をどうぞ。1月中に何も意見がなければ削っていこうと思います。

**Comment by cannorin** [comment]
Either is OK but I personally agree with this.
Twitter doesn't notice any updat

**Comment by cannorin** [comment]
↑ by mistake sorry

**Comment by chitoku-k** [comment]
+1
