### ISSUE TITLE
Read-only application cannot POST

### ISSUE THREAD

**Issue by punio** [CoreTweet/CoreTweet#124]
TwitterのApplicationをRead onlyで登録したとき

```csharp
Account.SettingsAsync()
```
で情報を取得しようとすると「Read-only application cannot POST」が返ってきちゃいますね。

MethodTypeを指定できると嬉しいんですが・・・

**Comment by azyobuzin** [comment]
POSTしてもデータ返ってくるからPOSTだけでいいや、という結論に至ったのですが、そういうこともあるのですね。

GET版のメソッドを新たに追加することを検討してみます。

**Comment by azyobuzin** [comment]
パラメータを1つも指定しなかったときに GET リクエストをするように修正しました
