### ISSUE TITLE
What  does PINCODE denote in the OAuth Get tokens merhod?

### ISSUE THREAD

**Issue by Ariel-Soft** [CoreTweet/CoreTweet#126]
Hello,
Can you please tell me what does "PINCODE" denote in the following line below:

var tokens = OAuth.GetTokens(session, "PINCODE");

Is it Pincode for the address?

It is throwing error "Invalid oauth_verifier parameter"

Thanks

**Comment by cannorin** [comment]
Read the documentation. 

https://github.com/CoreTweet/CoreTweet/wiki/Authentication
