### ISSUE TITLE
Decompressing streaming response

### ISSUE THREAD

**Issue by azyobuzin** [CoreTweet/CoreTweet#128]
#83 を再検討。圧縮されたレスポンスでもいけるんじゃないかという話。

まずはじめに、 HTTP のチャンク単位でのデータ取得。レスポンスストリームに対して大きめのバッファーで Read してみたところ、チャンク単位で読み取れている様子。このことからキリよくデータを取得することが可能だと思われる（現在の ReadLine でうまくいってるのもこのおかげだと思う）。

次にどう展開するか。

参考: [gzip圧縮されたデータの展開方法いろいろ - Qiita](http://qiita.com/mpyw/items/eb6ef5e444c2250361b5)

ストリーミングのレスポンスは Deflate のブロックのキリがいいところで 1 チャンクとなっているようなので、チャンクごとに DeflateStream を使って展開すればうまくいく。ただし 1 チャンクがバッファーより大きかった場合危険なので、ブロックがちょうどいいところで終わっているかチェックする必要がありそう。

というわけで技術的にいけそうな気がするんですけれども、結局ストリーミングのレスポンス読み取りだけすごく特別扱いしなくてはいけなくてクソ面倒なんですけどどう実装したらいいですか。あとこの issue のタイトルなんとかしたい。

**Comment by a4lg** [comment]
はい、圧縮されたチャンク自体はリアルタイムに送られているようです。

その解決策は**理論上は**不可能ではない、と、元のレポート (#83) を上げた者としては考えています……が、それをすると既存フレームワークに頼っている部分のほとんど (具体的に言えば Web リクエストの生成) を自前で実装する必要が出てくるようなんですよね。
実のところ、#83 の解決としては途中までその方向性を考えていましたが、作業量を見積もるととんでもないことになりそうでしたので、pull request としては当面の問題回避を優先した次第です。

Web リクエスト生成部分を (Windows プロキシの考慮等様々なケース含めて) 再実装することなく streaming のチャンクを都度取得できるようなら (具体的には gzip 圧縮されたストリームをそのまま読めるなら) 上記の指摘は誤りになると思います。その場合、deflate ストリームを何とか再解釈する (Deflate 実装を最悪独自実装する) ことになりますが……一応は、可能ではありそうです (かなりの [バッドノウハウ的な] hack にはなりそうですが……)。

**Comment by azyobuzin** [comment]
今のところ想定している実装は、 Deflate 1 ブロックごとに DeflateStream を使って展開かなぁと考えています。もうすでにバッドノウハウ…。

**Comment by a4lg** [comment]
それを行う場合、最低でも仰るとおりの Deflate (最低でもブロック境界を判定できる程度の) 実装が必要ですね。
また、環境的にも次の条件が必要です (内容としては先のコメントの言い換えとなります)。

1. Web リクエストライブラリにおいて、転送方式が GZIP / Deflate であることを正しく検出できること
2. Web リクエストライブラリにおいて、デコードされていない (GZIP や Deflate のままの) データをリアルタイムで受け取れるストリームを受け取れること

私の #83 報告時の調査では、少なくとも Mono 環境において 2. を満たすことができなさそうに見えました。`DeflateStream` クラスには `BaseStream` というプロパティがありますが、バッファリングによる細かい動作の差異があった場合に最悪バージョン違いで動かないということが考えられたため、信用していません。

私の見解が誤っていたら、申し訳ないですがご指摘願います (誤っていたらそれはそれで嬉しいので)。

**Comment by azyobuzin** [comment]
https://twitter.com/azyobuzin/status/723540072444764161

**Comment by azyobuzin** [comment]
生のデータを取るのは AutomaticDecompression をなしにして、自分で Accept-Encoding: gzip, deflate すればいけましたけど、これで問題ありますか？

**Comment by a4lg** [comment]
なるほど！System.Net 名前空間を使う場合にはそういう手があるのですね。
というわけで追加調査。AllowReadStreamBuffering プロパティ (ただしこちらは .NET 4.5 以降) も false に設定し、レスポンスのバッファリングを無効にするのが良さそうですね。

* https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.automaticdecompression%28v=vs.110%29.aspx
* https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.allowreadstreambuffering%28v=vs.110%29.aspx

全くの盲点でした。ありがとうございます。

ただ、そうなると UseCompressionOnStreaming を完全に削除するのには賛成できなくなります。.NET 3.5/4.0 ではバッファリングを無効にできない (メッセージの詰まりを否定できなくなる) わけですからね。あと、場合によっては "圧縮ストリーミングが可能か否か" をライブラリ側から示すような静的プロパティを実装する必要があるかもしれません。

**Comment by azyobuzin** [comment]
AllowReadBufferingBuffer は mono 3.x で SendChunked と競合するバグがあってやめた記憶があります。

そもそも HttpWebResponse によるバッファが問題なら、非圧縮のレスポンスでも同じ問題が起こるので関係ないような気がします。

**Comment by a4lg** [comment]
なるほど……。うーん、とりあえず、プロパティの削除には反対、圧縮ストリーミングの実装には賛成、と意見だけ述べておきます。

**Comment by azyobuzin** [comment]
Twitter ライブラリに組み込むコードとしては大掛かりすぎるなぁという感じ。うーんやめておこうかなぁ。

https://gist.github.com/azyobuzin/3d7d5d094066cdad1b7bc5b934d04337
