### ISSUE TITLE
Support netcoreapp1.0

### ISSUE THREAD

**Issue by azyobuzin** [CoreTweet/CoreTweet#130]
PCL だけでなく netstandard でも何種類か対応しておく必要がありそう。

依存するパッケージが prerelease 扱いなので、とりあえず現状のままで待って、 .NET Core 正式リリースに合わせようかな。（現状 `imports: "dnxcore50"` してもらわなければいけない）

**Comment by sudosan** [comment]
:+1:

**Comment by azyobuzin** [comment]
XamarinStudio が NuGet 3 になったころに PCL は消したいところ
