### ISSUE TITLE
Getting UserTimeLine throws exception

### ISSUE THREAD

**Issue by Kaliumiodid** [CoreTweet/CoreTweet#134]
I am currently using the following Code to get a user's timeline (Screen_name is replaced, but I think it should be the Twitter name without the @?):

OAuth2Token apponly = OAuth2.GetTokenAsync(CONSUMER_KEY, CONSUMER_SECRET).Result;
try
{
      var t = apponly.Statuses.UserTimelineAsync(screen_name: "exampleUser").Result;
}
catch (AggregateException ae)
{
      return;
}

When I get to the UserTimelineAsync-method, I get an exception saying:
Message = "One or more errors occurred. (The parameter is incorrect.\r\n\r\nInvalid HTTP headers.)"

The key and secret are correct, I already double-checked and it should work with just app-only authentication.

**Comment by azyobuzin** [comment]
I couldn't reproduce the exception in CoreTweet 0.7.1 on .NET Framework 4.6.1 and .NET Core. Please tell me your environment, for instance, .NET, UWP or Xamarin.

**Comment by Kaliumiodid** [comment]
Thank you for the quick response.
It's an UWP project using CoreTweet 0.7.1.345. The code is inside a class library, but also throws the exception in the Project containing the Mainpage. Beside CoreTweet and the Microsoft .NET-Core no more packages are used. Do you Need anything more?

**Comment by azyobuzin** [comment]
Thank you for reporting. I can reproduce the exception.

I'm attempting to fix this bug.

**Comment by azyobuzin** [comment]
I've fixed. To use fixed version, add https://ci.appveyor.com/nuget/coretweet-pvq86631pp8l as a NuGet source to your configuration and download CoreTweet 0.7.1.347.

Thank you very much :+1:

**Comment by Kaliumiodid** [comment]
Thank you for the quick help.
