### ISSUE TITLE
Support redirect flow (no PIN)

### ISSUE THREAD

**Issue by saxx** [CoreTweet/CoreTweet#135]
I'd like to use this fine library in my ASP.NET Core application. 

While the approach with `oob` und PIN would work, it would be nice to get the proper OAuth redirect flow working. Unfortunately there's only a `GetTokens()` method for a PIN. It would be nice to have another `GetTokens()` that expects (for example) the called callback URL to get the access tokens.

**Comment by azyobuzin** [comment]
`GetTokens`'s `pin` parameter is equivalent to `oauth_verifier` parameter in OAuth. So you can use `GetTokens` method for redirect flow.

Regretting we confused you, I'm planning to change the parameter name.

**Comment by saxx** [comment]
Thank you for the quick reply, it works beautifully :)

This is my very simple try-it-out scenario:

        private static OAuth.OAuthSession _session;

        public IActionResult TwitterStart()
        {
            _session = OAuth.Authorize("...", "...", Request.GetUri().ToString().Replace("Start", "End"));
            return Redirect(_session.AuthorizeUri.ToString());
        }

        public IActionResult TwitterEnd(string oauth_verifier)
        {
            var tokens = _session.GetTokens(oauth_verifier);
            var stati = tokens.Statuses.HomeTimeline(count => 10).ToList();
            return null;
        }

It seems I need to use the same `session` in `TwitterEnd` as in `TwitterStart`. Sure, I could store it in ASP.NET user session or something, but is there a better, built-in way for me to "re-create" the `session` in `TwitterEnd` instead of having to store it somewhere and re-use it?

**Comment by azyobuzin** [comment]
I recommend that you do the following way.

1. In TwitterStart, store `_session.RequestToken` and `_session.RequestTokenSecret` to ASP.NET's session store in secure way as you can.
2. In TwitterEnd, write `new OAuth.OAuthSession() { ConsumerKey = "your API key", ConsumerSecret = "your API secret", RequestToken = StoredRequestToken, RequestTokenSecret = StoredRequestTokenSecret }` to create new instance of OAuthSession.
