### ISSUE TITLE
Incompatible with ASP.Net Core Twitter Authentication

### ISSUE THREAD

**Issue by jchannon** [CoreTweet/CoreTweet#138]
I have an app that uses ` app.UseTwitterAuthentication()`, this logs the user in via twitter and then optionally stores an `access_token` and `access_token_secret`. It does not expose `oauth_verifier` so this cannot be used to authorize with this library which I think is the same value as `pin` in the authorize argument.  

Is there an alternative way to create a session to retrieve statuses using the `access_token` and/or `access_token_secret`?

**Comment by azyobuzin** [comment]
You can use `Tokens.Create` to make a `Tokens` instance from `access_token` and `access_token_secret`.

**Comment by jchannon** [comment]
Brilliant, thanks!
