### ISSUE TITLE
Don't know if this is the right place to post this issue...

### ISSUE THREAD

**Issue by oniblab** [CoreTweet/CoreTweet#139]
Hello everyone;
I have a twitter app using coretweet that works great already but i'm having problems with the rating limits in direct messages.
My app is in VB NET, and i normally use this to send a direct message:

```vb
Dim x as CoreTweet.DirectMessageResponse
Dim Name,Message as String
Name="Whatever user i want"
Message="Whatever Message i need to send"
x=tw.DirectMessages.[New](screen_name:=Name, text:=Message)
```

Of course, tw is defined like this:

```vb
Private tw as New CoreTweet.Tokens
```

And in the Load Event i have my tw.ConsumerKey, tw.ConsumerSecret, tw.AccessToken and tw.TokenSecret set.

The problem that i'm having is that from time to time i get an exception indicating that my rate limit has been exceeded. So, when i try to send a direct message from my app, or the twitter web page, i can't cause i'm blocked.

My question is: Is there a way for me to check the rating values for direct messages? When i use 

```vb
Dim x As CoreTweet.Core.DictionaryResponse(Of String, System.Collections.Generic.Dictionary(Of String, CoreTweet.RateLimit)) = tw.Application.RateLimitStatus()
```

and browse all the limits, there's none of them with its limits different than the remaining; only /application/rate_limit_status has its limits to 180 and remaining in 179.

If anyone can give me some light on this, i would appreciate it.

Thanks in advance.

**Comment by oniblab** [comment]
Sorry, but i also would like to point out that x is set to nothing when the rate limit occurs, so i don't have the rating values as a result, just an exception.

**Comment by azyobuzin** [comment]
You cannot get the rate limt of direct_messages/new because it is a POST API.

According to [the help](https://support.twitter.com/articles/249071), you can send 1,000 direct messages a day. But you will be blocked when you send many direct messages in a short time.

**Comment by oniblab** [comment]
Hello azyobuzin.
Well i guess that i'll have to create my own "rate control" inside the app or condense several messages in one to achieve my objective of not being blocked.
Thanks a lot for your comment and your time.
