### ISSUE TITLE
Instance of SearchResult

### ISSUE THREAD

**Issue by jchannon** [CoreTweet/CoreTweet#140]
Hi, I'm writing some unit tests on my app and I want to say my mock/fake returns a `SearchResult` with a `Status` inside it however everything I try fails to convert it from an array or List or ReadOnlyCollection to a `SearchResult`.

How can I construct a `SearchResult` with a `Status` in it?

**Comment by azyobuzin** [comment]
I found SearchResult.statuses is private. I will think of the way to construct a SearchResult from code.

As a workaround, you should deserialize a sample JSON to SearchResult with JSON.NET. I think it's easy way to make a test case.

**Comment by jchannon** [comment]
I will try but a deserialiser will try and create an instance of
SearchResult and add items to it which is the same issue I have.

How does CoreTweet construct an instance of SearchResult? I can't see it in
the code anywhere

**Comment by cannorin** [comment]
```csharp
using Newtonsoft.Json.Linq;
string json = dummyJson;
SearchResult sr = JToken.Parse(json).SelectToken("").ToObject<SearchResult>();
```

this should work

**Comment by jchannon** [comment]
This worked:

```
string json = "{\"statuses\":[{\"Text\":\"MVC Sucks, try #NancyFX\", \"Id\":1}]}";
SearchResult sr = JToken.Parse(json).SelectToken("").ToObject<SearchResult>();
```

Not entirely sure how the deserializer managed to do that though

**Comment by cannorin** [comment]
Newtonsoft.Json manages it: http://www.newtonsoft.com/json/help/html/SerializationAttributes.htm
See also: https://github.com/CoreTweet/CoreTweet/blob/master/CoreTweet.Shared/Objects/Status.cs#L514-L565

Everything in CoreTweet is mockable in the same way; all you have to do is prepare the JSON, parse it with ```JToken.Parse```, and then ```ToObject<DesiredType>```.
 
You can also use ```CoreTweet.Core.CoreBase.Convert<T>``` and ```CoreTweet.Core.CoreBase.ConvertArray<T>``` (for endpoints which return ```ListedResponse<T>```), which do the same thing.

**Comment by jchannon** [comment]
It would be good if statuses was public on SearchResult.  I don't think
deserializing json to an object is the correct approach for consumers of
the library.  What do you think?

Fro ListedResponse<T> I can actually deserialize as a List<T> without
needing the Convert calls

**Comment by azyobuzin** [comment]
I said I would make `SearchResult.statuses` public in one way and another in the first comment. Is it enough?

**Comment by jchannon** [comment]
Yes thanks, would you like me to send a PR?

**Comment by azyobuzin** [comment]
If you have a good suggestion, please send a PR.

**Comment by cannorin** [comment]
If you *could* access the ```SearchResult.statuses``` publicly, you *still* have to create ```Status```es by yourself.

Are you going to create a whole new instance in the user side? I don't think it is a good idea. 

So prepare the actual JSON response (use curl or something) and deserialise it.

**Comment by jchannon** [comment]
I think that's fine. Also you could have the constructor take in a list and
set the Statuses property in the constructor too

**Comment by cannorin** [comment]
Newtonsoft.Json creates objects without calling their constructor, and as we can create objects from JSON, I don't think constructors are needed.
Also, creating instances in the user side is pain, as they have a lot of properties you have to set.
Sorry, I'm not going to add any constructors to CoreTweet objects. This is because of my aesthetics in design and coding.

**Comment by jchannon** [comment]
But you as the library author don't need to worry about creating instances
of classes. Me as a user would but if a tweet has a lot of properties then
so be it. That's what Twitter defines for us so not a lot we can do about
it. We either have to set a lot of properties or write a lot of Json to
deserialize. No difference really.

**Comment by cannorin** [comment]
You really don't have to write any json!

Just use the actual response. There are an official tool to help this: https://github.com/twitter/twurl

**Comment by azyobuzin** [comment]
@cannorin I'm sorry to have said I would make it public in one way and another. I could not find a great way to solve this issue.

**Comment by jchannon** [comment]
But I don't want to have use tools or deserialize json just to set a
property. Seems wrong.

**Comment by azyobuzin** [comment]
Is your usage really unit tests? If it is, you should use the actual response to test your code rightly.
If you want a object that represents a list of tweets, you should create a class by yourself, because CoreTweet objects just represents responses from Twitter.

**Comment by jchannon** [comment]
Here's my example usage:

```
            var tweeter = A.Fake<ITweeter>();

            //SearchResult takes no constructor
            string json = "{\"statuses\":[{\"Text\":\"MVC Sucks, try #NancyFX\", \"Id\":1}]}";
            SearchResult sr = JToken.Parse(json).SelectToken("").ToObject<SearchResult>();

            A.CallTo(() => tweeter.Search("mvcsucks")).Returns(sr); //In the returns I can't do new SearchResult(){Statuses = new List<Status>(){new Status(){Text="MVC Sucks"}}}

```

**Comment by cannorin** [comment]
@azyobuzin No worries. This is my business.

@jchannon Okay, I'll try to explain how the 'just to set a property' turns out bad, despite it is an instant solution.

Let's think we are going to mock the search result window in our app.

---

First, we have to show the author decently: user icon, user name, and screen name. 

OK, let's set the ```User``` property.

Second, we have to display the source (client's name), retweeted count, favourited count, DateTime of when the Tweet was created, etc, etc...  I feel a headache coming on.

Lastly, we want to test whether the text shows properly. Is the URL become a link? Is the ```@screen_name``` become clickable? 

Those kind of information is described by the... [oh.](https://github.com/cannorin/CoreTweet/blob/master/CoreTweet.Shared/Objects/Entities.cs)

Okay okay, I managed it. Now we have to create so many things like this to test the list view of tweets.. WHAT!?

---

This is why you should use the actual response, instead of creating your own.

**Comment by jchannon** [comment]
But this sounds like you are coming from it at a different perspective. I'm not testing any UIs etc. This is a web app. If I want mock that the user property is instantiated that's my problem so if I have to set a billion properties so be it, there's nothing we can do about that, that's the structure Twitter have defined

**Comment by cannorin** [comment]
But we can avoid so many problems by using the actual JSON in all the cases. Why not?

**Comment by jchannon** [comment]
Because I'm trying to use C# the way its supposed to be used

**Comment by azyobuzin** [comment]
`ITweeter.Search` is not a member of CoreTweet. So you must design the interface by yourself.

Should `ITweeter.Search` return a `SearchResult`? I think `ITweeter.Search` calls a Twitter API and forms objects suitable for your application from the response, so it will return objects in your application, not in CoreTweet.

**Comment by jchannon** [comment]
ITweeter is my wrapper around Tokens. So it calls Tokens.Search.TweetsAsync which returns a SearchResult

**Comment by cannorin** [comment]
Yeah, so please use our library in the way we suppose to use. (lol)

Sorry, just a joke. But serialising and deserialising are always your friend to test something with data formats.

**Comment by cannorin** [comment]
Anyway, I'm pretty sure that using actual responses is the best way to write tests. 

And it takes few seconds to obtain the raw JSON response, save it to a file, and then do ```File.ReadAllText``` to import to your code.

When you want to add some functions to your app, this small effort will help you a lot.

**Comment by jchannon** [comment]
That's a terrible idea for unit tests however I'm clearly not going to win this 😄

**Comment by cannorin** [comment]
The input data shouldn't always be 'unit'... Using the actual response provides more extensibility, accuracy, reliability, and 'write and forget'-ability.

But... you can always fork this and edit as you like. Nothing stops you from doing so :P
