### ISSUE TITLE
Determine if delete was successful

### ISSUE THREAD

**Issue by jchannon** [CoreTweet/CoreTweet#142]
Is there a way to know if a tweet deletion was successful?

**Comment by azyobuzin** [comment]
If `Statuses.Destroy` returns the tweet, the deletion is successful.

**Comment by jchannon** [comment]
So it can be null or a populated?

**Comment by chitoku-k** [comment]
Throws `TwitterException` when it fails. Use `try-catch` so you could handle any exceptions.

**Comment by jchannon** [comment]
Thanks.

How do I create an instance of TwitterException? It has a private
constructor so I can't seem to create an instance of it.

**Comment by jchannon** [comment]
Thanks.

How do I create an instance of TwitterException? It has a private
constructor so I can't seem to create an instance of it.

Usage:

`A.CallTo(() => mytokensWrapperThatCallsDestroyAsync.DeleteTweet(999)).Throws(new TwitterException());`

I can simulate the DeleteTweet(DestroyAsync) with a fake and test what my app does when a `TwitterException` is thrown

**Comment by chitoku-k** [comment]
The static method `Create` can be used, however, it is not recommended that you create one because it is out of the unit test for your app.
