### ISSUE TITLE
This feature is temporarily unavailable

### ISSUE THREAD

**Issue by martingagne** [CoreTweet/CoreTweet#146]
First of all thank for the help. I am not sure if this is related to CoreTweet, my code or Twitter.

I am able to get an AccessToken. I get redirected to Twitter, I approve the app and then I am redirected back to my page. At that point I use the following function below to retrieve the ScreenName on the account. It works perfectly. When I refresh the page and execute the same method again (with the same creds, requestToken and oAuthVerifier), I get an exception on GetTokensAsync(...). The exeception is "This feature is temporarily unavailable" (Unauthorized). The only way I have to make this work again is to force the user to approve the app again. It is like if the token was good for a single use only...

        public async Task<string> GetScreenName(int tenantId)
        {
            var twitterHelper = new TwitterSettingManager(this.settingManager);
            var consumerCreds = await twitterHelper.GetConsumerCredentials();
            var requestToken = await twitterHelper.GetRequestToken(tenantId);
            var oauthVerifier = await twitterHelper.GetOAuthVerifier(tenantId);

            var oAuthSession = new OAuth.OAuthSession
            {
                ConsumerKey = consumerCreds.ConsumerKey,
                ConsumerSecret = consumerCreds.ConsumerSecret,
                RequestToken = requestToken.AuthorizationKey,
                RequestTokenSecret = requestToken.AuthorizationSecret,
            };

            var t = await oAuthSession.GetTokensAsync(oauthVerifier); // <-- Fails on this line on the second call. The first one works fine.
            return t.ScreenName;
        }

I do not understand because the same credentials worked just fine a few seconds before. Am I missing something oblivious?

**Comment by cannorin** [comment]
There are 2 types of "token" you will encounter in the OAuth authentication flow.

---

* Access token (```Tokens``` in CoreTweet)

An access token proves your identity (as a Twitter account) *when you use Twitter APIs from your app*.

You can/should reuse the same access token whenever you use the same Twitter account to call API endpoints from the same application, so this is the very thing you have to store in your machine.

---

* Request token (```OAuthSession``` in CoreTweet)

A request token proves your identity (as a person) *while you are requesting an access token for your app*.

Once you have obtained the access token, you have to forget about the request token, and if you want to login to another Twitter account, you have to create a new one.

The OAuth verifier (the thing you pass to ```oauthSession.GetTokens```) is only used to obtain the access token from the request token, so you have to forget about it too.

(This is why we call it a "session".)

---

See also: https://dev.twitter.com/web/sign-in/implementing

**Comment by cannorin** [comment]
Here is the tutorial with codes: https://github.com/CoreTweet/CoreTweet/wiki/Authentication
