### ISSUE TITLE
"Could't authenticate you" in Xamarin Forms PCL.

### ISSUE THREAD

**Issue by bkaankose** [CoreTweet/CoreTweet#148]
Latest version of CoreTweet fails to Authenticate with app key & app secret key. Keys are correct, valid internet connection but CoreTweet fails. What might be the reason behind this?

**Comment by cannorin** [comment]
It is possible that you have called an endpoint requiring the permission which is not available to your application  (ex. statuses/update without the 'write' permission).

Please let me know the method call which you have gotten the error on, and the permission which your application currently has (you can check it in the [Twitter Application Management](https://apps.twitter.com/) ).

Please see also the [troubleshooting](https://github.com/CoreTweet/CoreTweet/wiki/TroubleShooting).

**Comment by bkaankose** [comment]
I'm trying to get the authorization url with the OAuth.AuthorizeAsync. My application has read/write permission. @cannorin

**Comment by cannorin** [comment]
Please check the ```TwitterException.Errors[0].Code``` property using the exception dialog of Visual Studio.

If it is '32', your keys are invalid or ill-formed (ex. containing invalid characters such as '{' or '}').

If '135', CoreTweet is failing to generate timestamps. Please check your system clock.

If this does not solve the problem please tell me again, preferably with the stack trace and the actual code (with your keys masked).

**Comment by cannorin** [comment]
Hi, do you still have any problems? Please don't hesitate to let me know if you do.

**Comment by cannorin** [comment]
Should you encounter any problems again please leave a comment here, and I will reopen this issue.
