### ISSUE TITLE
TokensのUserIdとScreenNameが取得できない

### ISSUE THREAD

**Issue by Actionintint** [CoreTweet/CoreTweet#149]
```csharp
using System;
using CoreTweet;

class Program
{
    static void Main()
    {
        var token = Tokens.Create(CK, CS, AT, AS);
        Console.WriteLine($"{token.UserId}/{token.ScreenName}");

        var me = token.Users.Show(user_id);
        Console.WriteLine($"{me.Id}/{me.ScreenName}");
    }
 }
```
ver 0.8.1.394
下のコードはちゃんとUserIdとScreenNameが表示されるんですけど
上のだとnullが帰ってきてるみたいなんですが
なぜでしょうか

**Comment by azyobuzin** [comment]
https://github.com/CoreTweet/CoreTweet/wiki/%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E5%86%8D%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B にある通り、 `Tokens.UserId`, `ScreenName` は `GetTokens` でアクセストークンを取得した直後のみ取得でき、 `Tokens.Create` で作成した場合は取得できません。
