### ISSUE TITLE
Is possible authorize with my own Access token?

### ISSUE THREAD

**Issue by Marjani** [CoreTweet/CoreTweet#151]
I'm the only person using my program
Is it possible that I can use my Access Token to authenticate?

**Comment by Marjani** [comment]
@cannorin Could you guide me?
For example, how can I send a tweet?

**Comment by cannorin** [comment]
@Marjani And then follow the [quick tutorial](https://github.com/CoreTweet/CoreTweet/wiki/Quick-Tutorial) from the `Your first tweet`.
