### ISSUE TITLE
Get last tweet in stream

### ISSUE THREAD

**Issue by Marjani** [CoreTweet/CoreTweet#152]
I'm sorry to ask this simple question
How can I get all the tweets from persons who I am following with Stream API?

**Comment by cannorin** [comment]
Assume you have an object `Tokens tokens`:

```csharp
foreach(var status in tokens.Streaming.User().OfType<StatusMessage>().Select(x => x.Status))
{
    // do something with the tweet..
}
```

Use LINQ’s `Where` if you want to exclude retweets.

Note that [the streaming APIs are going to be removed in Tuesday June 19, 2018.](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/guides/us-ss-migration-guide)

At this time, we are not sure if and how CoreTweet will support the new Account Activity APIs.
