### ISSUE TITLE
How to send a tweet include multiple image?

### ISSUE THREAD

**Issue by liuziangexit** [CoreTweet/CoreTweet#153]
I know we can send a tweet with a single image like:
`tokens.Statuses.UpdateWithMedia(status => "test",
 media => new FileInfo(@"E:\OneDrive\杂项\UI图片\jiangzemin.png"));`

But i want to know how to send a tweet with multiple image.
Thank you.

And i will continue to [translate the wiki of CoreTweet to Chinese](https://github.com/CoreTweet/CoreTweet/wiki/Home(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)).

**Comment by azyobuzin** [comment]
Thank you for translating the wiki!

The example of uploading multiple image is here: https://github.com/CoreTweet/CoreTweet/wiki/Uploading-Image-and-Video-Howto

**Comment by liuziangexit** [comment]
@azyobuzin thank you so much! you did a great job!
