### ISSUE TITLE
System.Net.WebException リモートサーバーがエラーを返しました:(401) 許可されていません

### ISSUE THREAD

**Issue by HomoRiron** [CoreTweet/CoreTweet#154]

**Comment by liuziangexit** [comment]
(401) Unauthorized

Is your OAuth token/secret and access token/secret correct?

Double-check your token strings.

Consider getting a new token/secret.

Is your bearer token revoked? (app-only authentication)

Use the latest and valid bearer token.

**Comment by cannorin** [comment]
https://github.com/CoreTweet/CoreTweet/wiki/%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB%E3%82%B7%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0

**Comment by 204504bySE** [comment]
トークンを確認してもだめな場合は、PCの時計を確認してください。
特にUser streamは数分ずれているだけでも接続できません。
(このような状況だとVerifyCredencitalは普通に通るので紛らわしいです。)

**Comment by cannorin** [comment]
>本当に心当たりはありませんか？もし本当に心当たりのないエラーに出会った時には、次の事柄を明記して報告してください。
>
>    エラーを再現できるコードや、レスポンスの JSON データ
>    完全なエラーメッセージ
>    ほかに重要だと思うこと

I'll close this issue in 3 days if no further information is provided.
