### ISSUE TITLE
When searching tweet only getting RTs of tweets

### ISSUE THREAD

**Issue by 0xjavi** [CoreTweet/CoreTweet#167]
Basically on my program I want to find the ORIGINAL tweet with some keywords, but using:
tokens.Search.Tweets only thing I will find is retweets:

![image](https://user-images.githubusercontent.com/50259142/57175122-407ac880-6e48-11e9-9e57-7c5de18b74e8.png)

Is there another way to find only original tweets? Not just retweets?

**Comment by azyobuzin** [comment]
First, if you want to find only original tweets, you can add `-filter:retweets` to your query. See https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators .

Second, that Search API has recently been called "Standard search API".
https://developer.twitter.com/en/docs/tweets/search/overview
Using Standard search API, you can only find tweets published in the past 7 days. Tweets older than 7 days may be not shown in the results.

**Comment by 0xjavi** [comment]
Was following what you told me and did this:
```
public void test()
        {
            foreach (var tweet in tokens.Search.Tweets(q => txtKeyword.Text + " -filter:retweets", count => 2))
            {
                consola(tweet.User.ScreenName + Environment.NewLine + "ID: " + tweet.Id + Environment.NewLine + tweet.Text);
            }
        }
```
Didnt seem to work, was doing like before.
Tried oncoding the words and the filter to: csgo%20giveaway%20%2Dfilter%3Aretweets
Still pop ups RTed tweets;
![image](https://user-images.githubusercontent.com/50259142/57179782-dbdc5f80-6e81-11e9-84d9-7126d51e3d15.png)

Thanks!

**Comment by chitoku-k** [comment]
How about `-filter:nativeretweets`?

This is a somewhat weird technique from [About advanced TweetDeck features](https://help.twitter.com/en/using-twitter/advanced-tweetdeck-features) but hope this helps.

**Comment by 0xjavi** [comment]
Seems now it works, doesnt pop up IDs of retweets but I guess when someone retweets bumps the tweet to the top of the search. I guess I will need to save the tweets I already got inside a list. Thanks so much!
