### ISSUE TITLE
Source file CoreTweet.Shared\RestApis.cs could not be found.

### ISSUE THREAD

**Issue by ajitgoel** [CoreTweet/CoreTweet#168]
I have downloaded the sourcecode zip and unzipped it. Building the application throws the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file '$\CoreTweet-master\CoreTweet.Shared\RestApis.cs' could not be found.	CoreTweet (netstandard1.3)	$\CoreTweet-master\CoreTweet\CSC	1	Active

Can you please check?

**Comment by azyobuzin** [comment]
Please read the build instruction on README.md.

https://github.com/CoreTweet/CoreTweet#build

On Windows, run `build.ps1 -ExecuteTemplate` before building from the csproj. On other platform, run `make rest-apis`.

**Comment by ajitgoel** [comment]
Thank you azyobuzin.
