### ISSUE TITLE
I can't authenticate

### ISSUE THREAD

**Issue by boop5** [CoreTweet/CoreTweet#170]
I'm trying to use CoreTweet but I can't get it working. I created a Twitter App and passed all the keys and secrets. I can signup with another C# Twitter API. But I'd prefer to use this one.

```
var twitter = Tokens.Create(consumerKey: "..",
                            consumerSecret: "..",
                            accessToken: "..",
                            accessSecret: "..");
var tweets = await twitter.Search.TweetsAsync(...);
```

I get an exception saying *CoreTweet.TwitterException: 'Could not authenticate you.'*

-----

Callstack

> This exception was originally thrown at this call stack:
> 	CoreTweet.Core.InternalUtils.ResponseCallback.AnonymousMethod__29_0(CoreTweet.AsyncResponse)
> 	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
> 	CoreTweet.Core.InternalUtils.ReadResponse<T>(System.Threading.Tasks.Task<CoreTweet.AsyncResponse>, System.Func<string, T>, System.Threading.CancellationToken)
> 	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
>     ...
>     [Call Stack Truncated]

**Comment by cannorin** [comment]
Hmm, it works fine on my machine. Can you double-check the token strings are correct?

**Comment by boop5** [comment]
Okay I checked it and it did not work. I regenerated the access token and now it works. Well, my bad. sorry
