### ISSUE TITLE
 I don't know how to set up quick reply

### ISSUE THREAD

**Issue by kawasaki-ken** [CoreTweet/CoreTweet#172]
I get an error when I run this program.

var wmn = tokens.DirectMessages.WelcomeMessages.New(
                text => "message",
                quick_reply_type => "type:options ,options:{{label:aaa, description:test,metadata: external_id_1}}"
                );

I get an error.
CoreTweet.TwitterException: welcome_message.message_data.quick_reply: Unknown quick_reply type type:options ,options:{{label:aaa, description:test,metadata: external_id_1}} 

I don't know because I can't find any references. Please tell me how to set the parameters.

**Comment by kawasaki-ken** [comment]
class QuickReply
    {
        public string type { get; set; }
        public IList<Options> options { get; set; }

        public class Options
        {
            public string label { get; set; }
            public string description { get; set; }
            public string metadata { get; set; }
        }
}

{
List<QuickReply.Options> options = new List<QuickReply.Options>
                {
                    new QuickReply.Options{label = "aa",description = "test",metadata = "external_id_1"},new QuickReply.Options{label = "ab",description = "test2",metadata = "external_id_2"}
                };

                List<QuickReply> json = new List<QuickReply>
                {
                    new QuickReply{ type = "options",  options = options }
                };

                // 普通の JSON テキスト構築
                string jsonString = JsonConvert.SerializeObject(json);

                var wmn = tokens.DirectMessages.WelcomeMessages.New(
                text => "メッセージ",
                quick_reply_type => jsonString
                );
}
I get an error.

**Comment by kawasaki-ken** [comment]
[{\"type\":\"options\",
\"options\":
[{\"label\":\"aa\",\"description\":\"test\",\"metadata\":\"external_id_1\"},{\"label\":\"ab\",\"description\":\"test2\",\"metadata\":\"external_id_2\"}]
}]

**Comment by kawasaki-ken** [comment]
"{\"type\":\"options\",
\"options\":
[{\"label\":\"aa\",\"description\":\"test\",\"metadata\":\"external_id_1\"},{\"label\":\"ab\",\"description\":\"test2\",\"metadata\":\"external_id_2\"}]
}"

error

**Comment by cannorin** [comment]
There are classes for quick reply already: https://github.com/CoreTweet/CoreTweet/blob/b120a7eaf665502a016b4e0a3f3a3754643629d7/CoreTweet.Shared/Objects/DirectMessageEvents.cs#L129-L148

Try creating an instance of `QuickReply` and set it to `quick_reply_type`.

Note than you can use optional parameters like this:

```csharp
var wmn = tokens.DirectMessages.WelcomeMessages.New(
  text: "message",
  recipient_id: recipientId,
  quick_reply_type: new QuickReply {  ..  }
);
```

This provides better performance and more type safety. See https://github.com/CoreTweet/CoreTweet/wiki/Specifying-Parameters-Howto#using-optional-parameter .

**Comment by cannorin** [comment]
It looks like our definition of `direct_messages/welcome_messages/new` is wrong.

It should have been fixed with https://github.com/CoreTweet/CoreTweet/pull/157 but we somehow missed out. (btw the reason is the official documentation is completely garbage: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event. It tells almost nothing about `quick_reply`).

We can fix it and then release 1.1. Thoughts? @azyobuzin @acid-chicken

**Comment by cannorin** [comment]
This might work (not tested, though):

```
endpoint WelcomeMessageResponse New : Post direct_messages/welcome_messages/new
{
    description
    {
        Creates a new Welcome Message that will be stored and sent in the future from the authenticating user in defined circumstances.
    }
    jsonmap
    {
        "welcome_message" : {
            "name": $name,
            "message_data": {
                "text": $text,
                "quick_reply": $quick_reply,
                "attachment": {
                    "type": $attachment_type,
                    "media": {
                        "id": $attachment_media_id
                    }
                }
            }
        }
    }
    params
    {
        required string text
        optional QuickReply quick_reply
        optional string attachment_type
        optional long attachment_media_id
        optional string name
    }
    returns
    {
        The message template.
    }
}
```

**Comment by cannorin** [comment]
@kawasaki-ken In the meanwhile, I think this might work for you:

```csharp
var wmn = tokens.DirectMessages.WelcomeMessages.New(
  text => "message",
  quick_reply => new QuickReply{ .. }
);
```

The `QuickReply` type is already defined in CoreTweet: https://github.com/CoreTweet/CoreTweet/blob/master/CoreTweet.Shared/Objects/DirectMessageEvents.cs#L129-L148

**Comment by kawasaki-ken** [comment]
thank you
but
                QuickReplyOption[] options = new QuickReplyOption[2];
                options[0] = new QuickReplyOption();
                options[0].Label = "test";
                options[0].Description = "test";
                options[0].Metadata = "external_id_1";

                options[1] = new QuickReplyOption();
                options[1].Label = "test";
                options[1].Description = "test";
                options[1].Metadata = "external_id_2";


                QuickReply qr = new QuickReply();
                qr.Type = "options";
                qr.Options = options;
                    
                string jsonString = JsonConvert.SerializeObject(qr, new JsonSerializerSettings { DefaultValueHandling = DefaultValueHandling.Ignore });

                var wmn = tokens.DirectMessages.WelcomeMessages.New(
                text => "message",
                quick_reply_type => jsonString
                );

this is error.
why?

jsonString　= "{\"type\":\"options\",\"options\":[{\"label\":\"test\",\"metadata\":\"external_id_1\",\"description\":\"test\"},{\"label\":\"test\",\"metadata\":\"external_id_2\",\"description\":\"test\"}]}"

**Comment by cannorin** [comment]
We escape strings so putting serialized string as an argument is not supposed to work (i.e. that is intentional).

**Comment by kawasaki-ken** [comment]
Quick replay cannot be used with core tweet？

**Comment by cannorin** [comment]
Please see this: https://github.com/CoreTweet/CoreTweet/issues/172#issuecomment-631506770

**Comment by acid-chicken** [comment]
> It looks like [our definition of `direct_messages/welcome_messages/new`](https://github.com/CoreTweet/CoreTweet/blob/master/ApiTemplates/welcomeMessages.api) is wrong.
> 
> It should have been fixed with #157 but we somehow missed out that. (btw the root cause is the official documentation is completely useless here: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event. It tells almost nothing about `quick_reply`).
> 
> We can fix it and then release 1.1. Thoughts? @azyobuzin @acid-chicken

Yes, I've missed it (I'm sorry).

> This might work (not tested, though):
> 
> ```
> endpoint WelcomeMessageResponse New : Post direct_messages/welcome_messages/new
> {
>     description
>     {
>         Creates a new Welcome Message that will be stored and sent in the future from the authenticating user in defined circumstances.
>     }
>     jsonmap
>     {
>         "welcome_message" : {
>             "name": $name,
>             "message_data": {
>                 "text": $text,
>                 "quick_reply": $quick_reply,
>                 "attachment": {
>                     "type": $attachment_type,
>                     "media": {
>                         "id": $attachment_media_id
>                     }
>                 }
>             }
>         }
>     }
>     params
>     {
>         required string text
>         optional QuickReply quick_reply
>         optional string attachment_type
>         optional long attachment_media_id
>         optional string name
>     }
>     returns
>     {
>         The message template.
>     }
> }
> ```

I think so (can be implemented like [`direct_messages/events/new`](https://github.com/CoreTweet/CoreTweet/blob/master/ApiTemplates/directmessagesEvents.api)) too.
But I also think we should make `QuickReply.Type` enum like `TweetMode` if breaking changes are allowed.

**Comment by azyobuzin** [comment]
https://github.com/CoreTweet/CoreTweet/issues/172#issuecomment-631505513 looks good. It works on my environment 👍 

> I also think we should make `QuickReply.Type` enum like `TweetMode`

[The documentation](https://developer.twitter.com/en/docs/direct-messages/quick-replies/api-reference/options) says <q>Must be set to <code>options</code></q>. I'm not sure how the field will be extended in the future.

**Comment by acid-chicken** [comment]
> > I also think we should make `QuickReply.Type` enum like `TweetMode`
> 
> [The documentation](https://developer.twitter.com/en/docs/direct-messages/quick-replies/api-reference/options) says "Must be set to `options`". I'm not sure how the field will be extended in the future.

I found the quick reply had 2 types besides `options` (`text_input` and `location`) but they were removed over 2 years ago. (FYI: <https://twittercommunity.com/t/quick-reply-text-input-not-always-working/101728/4>)

I'm sorry for my opinion is unstable but it seems using abstract class or interface like below is better implementation in light of the fact other parameters existed in other quick reply types.

```csharp
public abstract class QuickReply : CoreBase
{
    [JsonProperty("type")]
    public abstract string Type { get; set; }
}

public class OptionsQuickReply : QuickReply
{
    [JsonProperty("type")]
    public override string Type { get; set; } = "options";

    [JsonProperty("options")]
    public OptionsQuickReplyOption[] Options { get; set; }
}

public class OptionsQuickReplyOption : CoreBase
{
    [JsonProperty("label")]
    public string Label { get; set; }

    [JsonProperty("metadata")]
    public string Metadata { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }
}
```
