### ISSUE TITLE
How to get live tweets from a account in realtime

### ISSUE THREAD

**Issue by wasimjee** [CoreTweet/CoreTweet#176]
suppose I am the follower of an account @abcd

and I want to get live tweets . can anyone please explain and provide sample code this to achieve

**Comment by cannorin** [comment]
You can use [Filter Streams API](https://coretweet.github.io/docs/classCoreTweet_1_1Streaming_1_1StreamingApi.html#a00c9ed7805f35f8643176cfac3a569f9) for that.

Assuming you have a token object `token`,

```csharp
// using System.Linq;
// using CoreTweet;
// using CoreTweet.Streaming;

var u = tokens.Users.Show("abcd');

foreach(var m in t.Streaming.Filter(follow: new []{ u.Id })
            .OfType<StatusMessage>()
            .Select(x => x.Status))
    Console.WriteLine("{0}: {1}", m.User.ScreenName, m.Text);
```

See [here](https://github.com/CoreTweet/CoreTweet/wiki/Using-Streaming-APIs) for details.

**Comment by wasimjee** [comment]
Thanks for your Message.

I mean to say like continuous streaming.
if the connection is disconnected, then it reconnects

**Comment by cannorin** [comment]
It's more like how to use LINQ or Rx (I used LINQ in the above example).

You can just do `while (true)`or if you are familiar with Rx `Observable.Retry` and `Observable.Repeat` will get the job done.

Call `token.Streaming.FilterAsObservable` instead of `token.Streaming.Filter` if you want to use Rx.

**Comment by wasimjee** [comment]
Thank, 

can i get the sample code so that I can understand beter

**Comment by wasimjee** [comment]
Have done using token.Streaming.Filter

but not getting the complete message on the tweet.  Is there a character limit.

any way to get full message from the tweet.

**Comment by cannorin** [comment]
The `Status` object should have a `FullText` field.

**Comment by cannorin** [comment]
(that sample code was from the era when tweets were limited to 140 characters)
