### ISSUE TITLE
invalid oauth_verifier parameter

### ISSUE THREAD

**Issue by vileolet** [CoreTweet/CoreTweet#179]
I've looked through issues and can't seem to find anything that works for me. I'm using the base example of

            var session = OAuth.Authorize(key, secret);
            Tokens tokens = session.GetTokens(pin);

where key and secret are my consumer key and secret respectively. I've signed up for a twitter dev account, retrieved my pin, and hardcoded it as the string pin. Upon clicking the button that should authenticate and post, I get the invalid oauth_verifier parameter exception. I've tried several solutions, and nothing seems to work.

**Comment by azyobuzin** [comment]
Have you read https://github.com/CoreTweet/CoreTweet/wiki/Authentication ? I hope this helps.

**Comment by vileolet** [comment]
I have, from top to bottom.

**Comment by azyobuzin** [comment]
I don't know what causes your issue. Can you give us the details of your situation?

- Environment (ASP.NET Core, UWP, .NET Framework, Xamarin, etc)
- Full program (without the actual secret key)
- What did you do manually (ex. launch a browser to open `session.AuthorizeUri`)

**Comment by vileolet** [comment]
Full program:

        private void TwitterPush()
        {
            // Twitter authorization
            string key = "***";
            string secret = "***";
            string pin = "***";
            var session = OAuth.Authorize(key, secret);
            Tokens tokens = session.GetTokens(pin);



            //Check for media and tweet loop
            if (string.IsNullOrWhiteSpace(FileTextBox.Text) && string.IsNullOrWhiteSpace(TweetContent.Text))
            {
                //Generic tweet for an empty box
                tokens.Statuses.Update(status => "Generic streaming notification! I'm live, playing a video game probably. https://twitch.tv/***");
            }
            else if (string.IsNullOrWhiteSpace(FileTextBox.Text) && !string.IsNullOrWhiteSpace(TweetContent.Text))
            {
                //Tweet for when filled
                tokens.Statuses.Update(TweetContent.Text);
            }
            else if (!string.IsNullOrWhiteSpace(FileTextBox.Text) && !string.IsNullOrWhiteSpace(TweetContent.Text))
                {
                MediaUploadResult mediaPic = tokens.Media.Upload(media: new FileInfo(FileTextBox.Text));
                tokens.Statuses.Update(status: TweetContent.Text, media_ids: (IEnumerable<long>)mediaPic);
            }
            else
            {
                MediaUploadResult mediaPic = tokens.Media.Upload(media: new FileInfo(FileTextBox.Text));
                tokens.Statuses.Update(status: "#newpic", media_ids: (IEnumerable<long>)mediaPic);
            }

        }

Using the .NET Framework, and I used System.Diagnostics.Process.Start(session.AuthorizeUri.AbsoluteUri); to get the pin.

**Comment by azyobuzin** [comment]
You are using the method `session.GetTokens` incorrectly. Results of `OAuth.Authorize` will be different each time. So you need to save `session.RequestToken` and `sessionRequestTokenSecret` and after getting the PIN, re-instantiate `OAuth.OAuthSession` using the saved tokens.

### Example 1: Interactive

```csharp
var session = OAuth.Authorize(key, secret);

System.Diagnostics.Process.Start(session.AuthorizeUri.AbsoluteUri);

var pin = Console.ReadLine(); // PIN from stdin

var tokens = session.GetTokens(pin);
```

### Example 2: Separated

```csharp
var session = OAuth.Authorize(key, secret);

// Write tokens to stdout because you can note the tokens
Console.WriteLine(session.RequestToken);
Console.WriteLine(session.RequestTokenSecret);

// Go to session.AuthorizeUri
```

```csharp
// Create an OAuthSession instance
var session = new OAuth.OAuthSession { 
    ConsumerKey = "***",
    ConsumerSecret = "***",
    // Use the tokens got in first time
    RequestToken = "***",
    RequestTokenSecret = "***"
};

var pin = "***";
var tokens = session.GetTokens(pin);
```

**Comment by cannorin** [comment]
https://github.com/CoreTweet/CoreTweet/wiki/Authentication

There are 2 types of "token" you will encounter in the OAuth authentication flow.

---

* Access token (```Tokens``` in CoreTweet)

An access token proves your identity (as a Twitter account) *when you use Twitter APIs from your app*.

You can/should reuse the same access token whenever you use the same Twitter account to call API endpoints from the same application, so this is the very thing you have to store in your machine.

---

* Request token (```OAuthSession``` in CoreTweet)

A request token proves your identity (as a person) *while you are requesting an access token for your app*.

Once you have obtained the access token, you have to forget about the request token, and if you want to login to another Twitter account, you have to create a new one.

The OAuth verifier (the thing you pass to ```session.GetTokens```, aka pin code) is only used to obtain the access token from the request token, so you have to forget about it too.

(This is why we call it a "session".)

---

See also: https://developer.twitter.com/en/docs/twitter-for-websites/log-in-with-twitter/guides/implementing-sign-in-with-twitter

**Comment by vileolet** [comment]
Implemented and fixed, thank you!
