### ISSUE TITLE
Thanks for adding v2 support!

### ISSUE THREAD

**Issue by andypiper** [CoreTweet/CoreTweet#183]
Hi there! Thanks for CoreTweet. Just to let you know we've added a listing on the Twitter [Tools & Libraries page](https://developer.twitter.com/en/docs/twitter-api/tools-and-libraries)

Our [Libraries and SDKs](https://twittercommunity.com/c/libraries-and-sdks/63) forum welcomes any further announcements.

**Comment by cannorin** [comment]
@azyobuzin Can you release the new version to NuGet or can you give me the permission to https://www.nuget.org/profiles/cannorin ? I don't have it for some reason I can't remember.

**Comment by azyobuzin** [comment]
@cannorin I have sent an invitation for NuGet. What will be the next version? 2.0.0?

**Comment by cannorin** [comment]
@azyobuzin I prefer 2.0. 2 years have passed from the last release...

**Comment by Cyral** [comment]
NuGet version is still 1.1

**Comment by azyobuzin** [comment]
I will review our status of support for v2 this weekend

**Comment by azyobuzin** [comment]
Some APIs have not been implemented. I made a list (#192).

The APIs that have already been implemented works well. By releasing a new version now, the users of CoreTweet will enjoy the new APIs and we can receive feedbacks.

@cannorin Can I release `master` as `2.0.0-beta.1` ?

**Comment by cannorin** [comment]
Yeah, let's do that.
