### ISSUE TITLE
I got 403 no matter what method I am calling...

### ISSUE THREAD

**Issue by KleinChiu** [CoreTweet/CoreTweet#196]
## Problem
I follow the wiki to auth, take the pin from the user, pass to program to obtain token, then emit request to API.

The program stopped by exception with HTTP status 403.
But my consumer secret is for Read&Write, so at least searching for tweets should be successful (although my final goal is to tweet on behalf).

## Environment
|Environment| Version |
|--|--|
|.Net Core console|.Net 6|
|CoreTweet|1.0.0.483|
|Visual Studio|2022|

## Secret
|Secret Property| Status |
|--|--|
| 3-legged | enable |
| require email | disabled |
| Permission | Read & Write |
| Callback URL | http://localhost |

## Sample code

Feel free to use the secret, I will revoke those soon. If it's my secret's problem, please let me know.

```cs
namespace Laboratory
{
    using CoreTweet;
    using System.Diagnostics;

    public static class Program
    {
        private const string ConsumerKey = "JzGIwTBrlgG5b5yZwvvkhF3Mm";
        private const string ConsumerSecret = "cqS2r1uFSxxMLxNHYg12MZ6JG1kwwSa3GJZ3NirA4QRtGZY62B";

        public static int Main(string[] args)
        {
            OAuth.OAuthSession session = OAuth.Authorize(Program.ConsumerKey, Program.ConsumerSecret);
            Process.Start(new ProcessStartInfo(session.AuthorizeUri.AbsoluteUri) { UseShellExecute = true });

            Console.WriteLine("Please input your auth pin (7 digits):");
            string pin = Console.ReadLine();

            Tokens tokens = session.GetTokens(pin);
            tokens.Search.Tweets("amazing");

            return 0;
        }
    }
}
```

**Comment by KleinChiu** [comment]
Thank you very much for reviewing.
I just got upgraded to Elevated, and the call finally got done.
Also, apologies for making trouble, I thought this is v2 ...

**Comment by KleinChiu** [comment]
Thank you very much for reviewing.
I just got upgraded to Elevated, and the call finally got done.
Also, apologies for making trouble, I thought this is v2 ...

**Comment by cannorin** [comment]
Sadly, CoreTweet does not have a full v2 API support yet.

@azyobuzin can we take some time to complete the v2 support and release v2 officially?

**Comment by KleinChiu** [comment]
Side-tracked, did I miss any caution that this lib requires Elevated? It will be good if its on the README

**Comment by cannorin** [comment]
@KleinChiu we've been lazy at following Twitter API changes, so I've just noticed the access level thing because of this issue. We will hopefully stabilize the v2 API support and release a new version so that you can use v2 APIs too, and add some docs regarding that topic.

**Comment by azyobuzin** [comment]
> @azyobuzin can we take some time to complete the v2 support and release v2 officially?

@cannorin sorry. I have no time to develop CoreTweet until January.
