### ISSUE TITLE
User object does not have 'following' and 'notifications' properties

### ISSUE THREAD

**Issue by chitoku-k** [CoreTweet/CoreTweet#79]
Although 'following' and 'notifications' are to be removed from all of the responses, they can be still useful when retrieving a list of users.
As the library it should also contain deprecated properties and mark them obsolete with attributes if necessary.

See also:
Deprecation of following and notification elements - Google Groups
https://groups.google.com/forum/#!topic/twitter-development-talk/QrqIO5-OPG4

**Comment by azyobuzin** [comment]
I'll close this issue as we don't have to support deprecated fields which are not implemented in CoreTweet now.
