### ISSUE TITLE
When "IEnumerable<byte>" parameter used for media uploading,the request times out,  or "503" error occurs.

### ISSUE THREAD

**Issue by pierre3** [CoreTweet/CoreTweet#92]
In the following code, the request times out, or "503 Service Unavailable error" is returned after waiting a few minutes.
```cs
byte[] imageData = getImageBytes();  //Returns a byte array (size of about 70KB)
var res = tokens.Media.Upload(media => imageData);
```
There is no problem in the case of using the stream.
```
MediaUploadResult res;
using (var stream = new System.IO.MemoryStream(imageData))
{
    res = tokens.Media.Upload(media => stream);
}
// OK!
```
There are similar problems in other upload methods.
- Media.UploadAsync
- Statuses.UpdateWithMedia
- Statuses.UpdateWithMediaAsync

Perhaps, I think there is a problem with the `valueBytes.ForEach(b => stream.WriteByte(b));` in the `Request.WriteMultipartFormData` method .

See `Request.WriteMultipartFormData` method in [./CoreTweet.Shared/Request.cs](https://github.com/CoreTweet/CoreTweet/blob/master/CoreTweet.Shared/Request.cs)
```cs
private static void WriteMultipartFormData(Stream stream, string boundary, IEnumerable<KeyValuePair<string, object>> prm)
{
    //...
    
    if(valueStream != null) 
    { 
        while (true) 
        { 
              var buffer = new byte[4096]; 
              var count = valueStream.Read(buffer, 0, buffer.Length); 
              if (count == 0) break; 
              stream.Write(buffer, 0, count); 
        } 
    } 
    else if(valueBytes != null) 
        valueBytes.ForEach(b => stream.WriteByte(b));   //<-!!!
        //Data is sent by the number of times of valueBytes.Length.
        //Number of transmissions is too much.
    else 
        stream.WriteString(valueString); 
    
    //...
}
```

**Comment by azyobuzin** [comment]
Also in .NET uploads the bytes one by one, but it can accomplish the upload...
