### ISSUE TITLE
filename field is illegal in multipart/form-data

### ISSUE THREAD

**Issue by azyobuzin** [CoreTweet/CoreTweet#93]
It accepts only US-ASCII and the file name containing `"` may cause a bug.

https://github.com/CoreTweet/CoreTweet/blob/68c3a7b007f3141f9b7c1a23d6a027a1f3f19f7b/CoreTweet.Shared/Request.cs#L89

**Comment by lambdalice** [comment]
how's that for

```csharp
if(valueFile != null)
    stream.WriteString(String.Format(@"; filename=""{0}""", valueFile.Name.Replace('"','_')));
else
````
?
