### ISSUE TITLE
UriFormatExceptionが発生してUsers.Lookupでデータ取得できません.

### ISSUE THREAD

**Issue by otoroshi** [CoreTweet/CoreTweet#95]
ホームページの設定に.comなどを指定している場合発生するようです。
<pre>
CoreTweet.ParsingException: on a REST api, cannot parse the json ---> System.UriFormatException: 無効な URI: ホスト名を解析できませんでした。
   場所 System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   場所 System.Uri..ctor(String uriString)
   場所 CoreTweet.Core.UriConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IWrappedCollection wrappedList, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IWrappedCollection wrappedList, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   場所 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   場所 Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   場所 Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   場所 Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, Boolean isNullable)
   場所 Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   場所 Newtonsoft.Json.Linq.JToken.ToObject[T]()
   場所 CoreTweet.Core.CoreBase.ConvertBase[T](String json, String jsonPath)
   --- 内部例外スタック トレースの終わり ---
   場所 CoreTweet.Core.CoreBase.ConvertBase[T](String json, String jsonPath)
   場所 CoreTweet.Core.CoreBase.ConvertArray[T](String json, String jsonPath)
   場所 CoreTweet.Core.TokensBase.AccessApiArrayImpl[T](MethodType type, String url, IEnumerable`1 parameters, String jsonPath)
   場所 CoreTweet.Core.TokensBase.AccessApiArray[T,TV](MethodType type, String url, TV parameters, String jsonPath)
   場所 CoreTweet.Rest.Users.Lookup[T](T parameters)
</pre>

**Comment by lambdalice** [comment]
お使いの環境をお知らせください。(Windows なのか Mono なのか、.NET 3.5 〜 4.5・WP・ストアアプリなどののどれで動かしているのか、Mono の場合は ```mono --version``` の出力、具体的にエラーが発生するユーザ名など)

Mono 3.2.8 で C# REPL でテストした結果、

    tokens.Users.Lookup(screen_name => "amazon")
    // { 20793816 }

となり再現しませんでした。

**Comment by otoroshi** [comment]
動作環境は
windows7 32bit
.NET4.5
VC2012 Express For windows Desktop
で作成しています。

screen_name、@darrenhgraves
という方の情報でエラーが発生しています。
ユーザープロフィールが".com"になっていて、
Url("http://.com")でホスト名が不正になっています。
